### ISSUE TITLE
Support intellij-platform-gradle-plugin 2.0.0-rc

### ISSUE THREAD

**Issue by joshuataylor** [134130/intellij-mise#11]
Hi!

[IntelliJ Platform Gradle Plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin) has been moving really quickly as a result of fantastic work by @hsz (seriously, the Developer Experience is now much nicer!).

One great feature of the upcoming 2.0.0 release that would be super handy for this plugin is there is now much better experience when developing for multiple IDEs, which this plugin will have to accomodate for, eg IDEA, PyCharm, GoLand and the million other IDEs JetBrains now has, which would help with testing specific IDEs.

The good thing is that it's fairly straight forward to migrate (I've moved a couple of plugins, some small.. one rather larger), let me know if you want me to contribute this change.

It should hopefully be a version bump in [libs.versions.toml](https://github.com/134130/intellij-mise/blob/refs/heads/main/gradle/libs.versions.toml), [gradle.properties](https://github.com/134130/intellij-mise/blob/refs/heads/main/gradle.properties), then updating [build.gradle.kts](https://github.com/134130/intellij-mise/blob/refs/heads/main/build.gradle.kts) with the new syntax.

[Docs](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html)
[Migration to 2.0](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html)

**Comment by 134130** [comment]
Thank you for your interest!

Yes. I'm subscribing JetBrain's next version, and I've checked the [v2.0.0](https://github.com/JetBrains/intellij-platform-gradle-plugin/releases/tag/v2.0.0) is just released after 2 hours of your post!

I will gonna migrate this plugin, after #10 !

**Comment by joshuataylor** [comment]
I can share what I got done so far, let me create a PR for your puruseal.

I got stuck at the runConfiguration in the xml.

I also started with pythoncore, once that works, pythonid should be pretty much the same code, hopefully.

Once that's all in, we can add virtualenv support so it should set the virtualenv similar to Go! Woo!!

**Comment by 134130** [comment]
Cool! I'll check it out and make a PR with assigning you as a reviewer!
