### ISSUE TITLE
mise env still do not auto-load when using Run/Debug Configurations

### ISSUE THREAD

**Issue by songkg7** [134130/intellij-mise#116]
**Describe the bug**
unfortunately, mise env still do not load when using Run/Debug Configurations

**To Reproduce**

1. Create a Gradle project
2. Paste `println("HELLO: ${System.getenv("HELLO")}")` at `build.gradle.kts`
3. `$ mise set HELLO=WORLD`
4. Enter `ctrl + ctrl` to call `Run Anything` window
5. Execute `./gradlew clean` within `Run Anything` window
6. `HELLO: null` is output

**Expected behavior**

- if open `Edit Configurations > Environments > Edit environment variables`, mise env variables shoud be registered
- `HELLO: WORLD` should be printed

**Screenshots**

<img width="612" alt="image" src="https://github.com/user-attachments/assets/5cf55ac8-af53-432f-85b9-f32d946aa2b9" />

Can't find 'HELLO' env

<img width="1810" alt="image" src="https://github.com/user-attachments/assets/fbf586c6-13fe-4e77-a360-6612ab2ec0ba" />

HELLO is null but expected printing WORLD

**Desktop (please complete the following information):**

- OS: MacOS
- IntelliJ version: Ultimate 2024.3.1.1
- Mise Plugin version: 3.2.2

**Additional context**
[issue-project.zip](https://github.com/user-attachments/files/18248228/dummy.zip)

**Comment by 134130** [comment]
Hi @songkg7, thank you for your report!

The issue was resolved in #117 and it will be appeared in `v3.2.3`.
