### ISSUE TITLE
Add support for idiomatic version files

### ISSUE THREAD

**Issue by adamnfish** [134130/intellij-mise#118]
While mise has its own config file, it also offers interoperability with other configuration formats, many of which are described as [idiomatic version files](https://mise.jdx.dev/configuration.html#idiomatic-version-files) in the documentation.

As far as I can tell, this plugin doesn't appear to be loading versions of tools from these additional locations. Would it be possible to add some or all of these other supported mise configuration locations?

Chief among these is the `.tool-versions` file, but I'm also using `.nvmrc` in some projects and I'm sure many people will be using other idiomatic configuration files.

Apologies if I've missed something, and thank you!

**Comment by 134130** [comment]
Hi @adamnfish 

Thank you for your suggestion! However, intellij-mise uses the mise executable, no parsing the version files itself, so the tool selecting is owned by mise cli. So the idiomatic version files are now loading well. See the screenshot:

![image](https://github.com/user-attachments/assets/d164fc5e-cb4e-4c8a-ac11-bcb57c0cd5d9)

Let me know if there is any i missed. Thanks!

**Comment by adamnfish** [comment]
ok, thanks.

I had hoped this plugin would mean I wouldn't need to switch mise to use shims, but it sounds like that's the cause of my problems!

Happy New Year ❤️
