### ISSUE TITLE
Use mise ls --offline

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#48]
`mise ls` can be slow now. I think this plugin should use the new `--offline` flag (https://github.com/jdx/mise/issues/2949)
https://github.com/134130/intellij-mise/blob/587b263c7ff40e59ca94734abb51c6b908785b07/modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseCmd.kt#L41

**Comment by hverlin** [comment]
Thanks! I think it's what causing the IDE to freeze on startup with the latest version

**Comment by 134130** [comment]
@hverlin Hi, I've added this feature in v2.2.0. It will be available in JetBrains Marketplace soon. Thanks!
