### ISSUE TITLE
Deno support for IntelliJ

### ISSUE THREAD

**Issue by itsbradd** [134130/intellij-mise#50]
Thank you for this plugin! It has helped me a lot when working with Go and NodeJS. 
Could you provide support for Deno, such as automatically detecting the Deno version?

**Comment by 134130** [comment]
I'll check it soon!

**Comment by 134130** [comment]
Hi, @itsbradd

Is this settings page is what you want to change automatically, right?

**Comment by itsbradd** [comment]
No, You need to Install Deno plugin for IntelliJ first, then you will have the settings for Deno.
I want to use Mise to manage Deno, not NodeJS. Your plugin support for NodeJS work great already.

<img width="983" alt="image" src="https://github.com/user-attachments/assets/c89b06de-4e8e-4e98-be5c-70e9caf81fb4">

**Comment by 134130** [comment]
@itsbradd 

Sorry, It maybe unavailable by the same reason for this.
- https://github.com/134130/intellij-mise/issues/29

**Comment by 134130** [comment]
@itsbradd Hi, I found the way. The release v2.3.0 will bind it. Thank you for using this plugin!

**Comment by itsbradd** [comment]
Hi @134130 , thank you for your hard working.
I just checked and confirmed that your plugin correctly detects Deno installed by Mise. However, the path is not perfect yet; it’s missing /bin/deno.
Example: The correct path is /Users/brad/.local/share/mise/installs/deno/2.0.5/bin/deno
<img width="984" alt="image" src="https://github.com/user-attachments/assets/77619f2e-0bda-447d-8e69-94889218cf93">

**Comment by 134130** [comment]
@itsbradd

Hi, sorry for my bad. I've just released v2.4.0 again. Thanks!
