### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#62]
Some ideas I have for this plugin. Please let me know if you are interested, I can make PRs.

- Supports for additional languages / tools (Python. Rust, ...)

- Add a notification (e.g. on startup) if the user needs to run `mise install`

- add icon in `*mise.toml` to reload the mise configuration. I imagine that this could reload be used to run `mise install` and reload the SDKs (similar to what IntelliJ has for Gradle or Cargo.toml)
<img width="449" alt="image" src="https://github.com/user-attachments/assets/6dfdf10f-6ae2-468d-bdca-b7d6dee87eb7">

- Add a panel with tasks, env & tools (similar to `npm` or `gradle`)
<img width="463" alt="image" src="https://github.com/user-attachments/assets/b2aef18f-b0bd-4744-83e6-0038479643d2">

- Add a `mise` panel in settings:
  - Add checkbox to automatically load mise env
  - Add an input to specify which `mise` [profile](https://mise.jdx.dev/profiles.html#profiles) (`--profile` option) to use

- Add run configuration for mise and allow running tasks from `mise.toml` files (here is an example with `package.json` files)
<img width="282" alt="image" src="https://github.com/user-attachments/assets/dc07afb3-1abf-4cf0-919c-42293b1e4436">

- better autocomplete for `mise.toml` files. (there is already a [json schema](https://github.com/SchemaStore/schemastore/blob/1c1b31244bb2154b7904ba3f704d8f975bb22455/src/api/json/catalog.json#L5541-L5551), but maybe some small improvements could be made (like autocompleting task names in `depends`)
<img width="463" alt="image" src="https://github.com/user-attachments/assets/5ac83d27-bd6f-4612-9ea9-22e30461e1f2">

**Comment by 134130** [comment]
Thank you for your suggestion and interest in this plugin!

I love these :heart:
Almost everything is what I thought, too!

Actually, the plugin is just my personal usage, and I never thought the people were willing to use my plugin.

And as mise's original developer does, I use mise in my CLI more often, so that's why I did not add many features to it.

I'll make the several sub-issues and I'll take a shot.

Thank you for your suggestions again!

**Comment by hverlin** [comment]
Nice! I think the most important for me is to have the settings panel. I can create a few issues

> the plugin is just developed for my personal usage, and I never thought the people were willing to use it

If you prefer to keep yours simple, I don't mind creating another one 😅 I feel it might be better to have a single good plugin in the IntelliJ marketplace though :)

**Comment by 134130** [comment]
Never mind! It's my enjoy 😆

**Comment by hverlin** [comment]
Thank you! I will close this task in favor of individual issues
