### ISSUE TITLE
Does this support loading JDKs (other tools) from a `.mise.toml` file ?

### ISSUE THREAD

**Issue by dkowis** [134130/intellij-mise#7]
Thanks!

**Comment by 134130** [comment]
No, currently not. 😭

I really expected to integrate all of mise configuration, including `tools`, but there was some huddle. I'll search some ways for IDEA(JDK) firstly.

Thank you for your suggestion!

**Comment by 134130** [comment]
@dkowis Let me know more detailed requirements.

| Gradle | Maven |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/e5badd04-5ed8-46b8-97c5-5ed365aafd19) | ![image](https://github.com/user-attachments/assets/efa13f58-44e4-4c2e-be95-1bc981bec5f4) |



Do you want to set above settings?

**Comment by dkowis** [comment]
I'm less worried about setting maven and gradle, since I tend to use the wrapper (gradlew, or mvnw) and IDEA already supports those. 

I think a good feature would be to have it pick up the Project JDK from the mise configuration so that I don't have to manually go set the JDK.

**Comment by 134130** [comment]
I've figured out. Give me some time :)
![image](https://github.com/user-attachments/assets/4a252cf5-7b9c-4e1d-9196-ef025640f4b7)

**Comment by 134130** [comment]
Hi, I've just added support for the JDK and Go SDK.
It's now on review of Jetbrains Marketplace, but you can install it right [here](https://plugins.jetbrains.com/plugin/24904-mise/versions/stable/574952).

I made the mistake of deleting the plugin during the plugin upgrade process 🥲. so please delete the old version of the plugin.

Let me know if you have any other inconvenience. Thanks!

**Comment by 134130** [comment]
Now you can get it on marketstore. As I said before, I made the mistake of deleting the plugin before. So you need to reinstall with the new version. Thanks!

https://plugins.jetbrains.com/plugin/24904-mise/versions/stable/576406

**Comment by dkowis** [comment]
Awesome! I'll give it a shot!

**Comment by dkowis** [comment]
It's working great! It's picking up my ~/.config/mise/config.toml (even though it doesn't say that, its says it's getting it from the project) and auto setting up the JDK for me :D

**Comment by 134130** [comment]
Thanks! If you have any other suggestions, please feel free to submit the issue. ;D
