### ISSUE TITLE
A setting to configure path to `mise` binary

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#70]
- `mise` might not be available in path. It might also be that one is building `mise` locally and wants to refer to another version.
- Add a setting to configure the path to `mise`

Probably if one installs the extension and `mise` is missing on the system, it should show a notification that invites the user to configure the `mise` path or install it

**Comment by 134130** [comment]
Trying, but it is annoying to handle windows os. 🥲

**Comment by 134130** [comment]
> I added that setting in https://github.com/hverlin/mise-vscode, but I did not try to run `mise` on windows yet 😅 Does it work well?

I do not have windows too 😅
Mise started to support windows recently, so I think it is enough to support posix only.
