### ISSUE TITLE
Verify that all tools are installed on startup

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#71]
On startup, the extension should check that all tools are installed. If a notification indicates that some tools are missing, there should be an action to run `mise install` automatically

**Comment by 134130** [comment]
Thanks! The feature is implemented! 🎉 

- https://github.com/134130/intellij-mise/blob/cf44edf1de3dcd07d7e8b73d477f9460ea0a409e/modules/core/src/main/kotlin/com/github/l34130/mise/core/setup/AbstractProjectSdkSetup.kt#L81-L95
