### ISSUE TITLE
Right-click → run file does not load env. Variables

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#77]
If the user runs the file directly with right-click, run file, it won't load the mise env. variables.
It only works if the user visits the run configuration UI at least once.

**Comment by 134130** [comment]
Now, we support project-wide mise config settings, not only for each run configuration.

So, in my opinion, I think we don't need to enable "using mise envvar" for run configurations automatically.

Can we close this issue?

**Comment by hverlin** [comment]
yeah, this is obsolete 👍
