### ISSUE TITLE
Latest Intellij and mise plugin do not seem to cooperate any more

### ISSUE THREAD

**Issue by dkowis** [134130/intellij-mise#81]
```
❯ mise --version
2024.8.6 macos-arm64 (2024-09-26)
```

Intellij Version:
```
IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 12, 2024
Licensed to David Kowis
Subscription is active until September 17, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ml.llm (243.21565.202)
  com.intellij.grazie.pro (0.3.346)
  com.plugin.samusprogressbar (1.3)
  org.asciidoctor.intellij.asciidoc (0.43.2)
  com.github.lipiridi.spotless-applier (1.0.4)
  google-java-format (1.24.0.0)
  com.github.l34130.mise (2.5.0)
Kotlin: 243.21565.193-IJ
```

This is from opening a brand new project template created at start.spring.io.

![image](https://github.com/user-attachments/assets/11df39a8-1fcd-45f7-a275-e04aae7a63ad)

**Comment by hverlin** [comment]
You need to update `mise` using
```
mise self-update
```

**Comment by dkowis** [comment]
Ah, I had installed it from cargo in the past, and I regularly do `cargo install-update --all` so I hadn't thought of doing this.

**Comment by 134130** [comment]
@dkowis Thank you for your reporting!

I've never thought that `--profile` flag is really newer feature. I'll check more sensitively for backward compativility in later releases.

I apologize for the inconvenience.

**Comment by 134130** [comment]
@hverlin Thank you for your quick response too!

**Comment by hverlin** [comment]
My fault, I also thought it existed for a while. I think another issue is that mise does not prompt you to update every week or so. Only if you run `mise doctor` I think

**Comment by dkowis** [comment]
![image](https://github.com/user-attachments/assets/1a13c3dc-01c7-473f-ad89-4b999d177a46)
Just to close the loop on this, that very much did solve my problem! 

I'll add to my weekly desktop mainetnance to `mise self-update` (it used to be handled as part of `cargo install-update --all`

Thanks!
